#create SQLite Database

This notebook loads the cleaned retail orders dataset and stores it inside a SQLite database.

The database will be used for SQL analysis and Power BI visualization.

In [1]:
import pandas as pd
import sqlite3
from pathlib import Path

In [2]:
cleaned_data_path = Path("../data/processed/orders_cleaned.csv")

df = pd.read_csv(cleaned_data_path)

print("Cleaned dataset loaded successfully")
print("Shape:", df.shape)

df.head()

Cleaned dataset loaded successfully
Shape: (1200, 14)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [3]:
database_folder = Path("../database")
database_folder.mkdir(parents=True, exist_ok=True)

database_path = database_folder / "orders_cleaned.sqlite"

print("Database path:", database_path)

Database path: ..\database\orders_cleaned.sqlite

In [4]:
connection = sqlite3.connect(database_path)

df.to_sql(
    name="cleaned_orders",
    con=connection,
    if_exists="replace",
    index=False
)

connection.close()

print("SQLite database created successfully")

SQLite database created successfully

In [6]:
connection = sqlite3.connect(database_path) #check if table was createdd

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    connection
)

connection.close()

tables

             name
0  cleaned_orders

In [7]:
connection = sqlite3.connect(database_path) #check row count from database

row_count = pd.read_sql_query(
    "SELECT COUNT(*) AS total_rows FROM cleaned_orders;",
    connection
)

connection.close()

row_count

   total_rows
0        1200

In [8]:
connection = sqlite3.connect(database_path) #preview databse table

preview = pd.read_sql_query(
    "SELECT * FROM cleaned_orders LIMIT 5;",
    connection
)

connection.close()

preview

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04